from dataclasses import dataclass


@dataclass(frozen=True)
class Watchlist:
    id: str
    name: str
    description: str
    tickers: tuple[str, ...]


WATCHLISTS = (
    Watchlist(
        id="quality-core",
        name="All Quality",
        description="Large, liquid US leaders across major sectors.",
        tickers=(
            "AAPL",
            "MSFT",
            "NVDA",
            "AMZN",
            "GOOGL",
            "META",
            "AVGO",
            "TSLA",
            "JPM",
            "V",
            "MA",
            "BRK-B",
            "UNH",
            "LLY",
            "JNJ",
            "ABBV",
            "XOM",
            "CVX",
            "CAT",
            "GE",
            "HON",
            "COST",
            "WMT",
            "PG",
            "KO",
            "PEP",
            "NEE",
            "LIN",
            "PLD",
            "AMT",
        ),
    ),
    Watchlist(
        id="technology",
        name="Technology",
        description="Mega-cap software, platforms, payments, and infrastructure.",
        tickers=(
            "AAPL",
            "MSFT",
            "NVDA",
            "AVGO",
            "ORCL",
            "CRM",
            "ADBE",
            "NOW",
            "AMD",
            "INTC",
            "QCOM",
            "TXN",
            "ANET",
            "PANW",
            "CRWD",
        ),
    ),
    Watchlist(
        id="ai-semiconductors",
        name="AI / Semiconductors",
        description="Semiconductor and AI infrastructure leaders.",
        tickers=(
            "NVDA",
            "AVGO",
            "AMD",
            "TSM",
            "ASML",
            "AMAT",
            "LRCX",
            "KLAC",
            "MU",
            "MRVL",
            "QCOM",
            "TXN",
            "ARM",
            "ANET",
            "SMCI",
        ),
    ),
    Watchlist(
        id="financials",
        name="Financials",
        description="Large banks, card networks, asset managers, and insurers.",
        tickers=(
            "JPM",
            "BAC",
            "WFC",
            "GS",
            "MS",
            "C",
            "V",
            "MA",
            "AXP",
            "BLK",
            "SCHW",
            "CB",
            "MMC",
            "AIG",
            "ICE",
        ),
    ),
    Watchlist(
        id="healthcare",
        name="Healthcare",
        description="Large pharma, managed care, devices, and diagnostics.",
        tickers=(
            "LLY",
            "UNH",
            "JNJ",
            "ABBV",
            "MRK",
            "ABT",
            "TMO",
            "ISRG",
            "DHR",
            "AMGN",
            "PFE",
            "BSX",
            "SYK",
            "MDT",
            "GILD",
        ),
    ),
    Watchlist(
        id="defense-industrials",
        name="Defense / Industrials",
        description="Defense primes, aerospace, machinery, and industrial leaders.",
        tickers=(
            "LMT",
            "RTX",
            "NOC",
            "GD",
            "BA",
            "GE",
            "CAT",
            "DE",
            "HON",
            "ETN",
            "EMR",
            "PH",
            "UNP",
            "UPS",
            "URI",
        ),
    ),
    Watchlist(
        id="energy",
        name="Energy",
        description="Large integrated energy, producers, and oilfield services.",
        tickers=(
            "XOM",
            "CVX",
            "COP",
            "EOG",
            "SLB",
            "MPC",
            "PSX",
            "VLO",
            "OXY",
            "HAL",
            "BKR",
            "WMB",
            "KMI",
            "OKE",
            "LNG",
        ),
    ),
    Watchlist(
        id="consumer",
        name="Consumer Leaders",
        description="Consumer staples and durable discretionary leaders.",
        tickers=(
            "COST",
            "WMT",
            "PG",
            "KO",
            "PEP",
            "MCD",
            "SBUX",
            "NKE",
            "HD",
            "LOW",
            "TGT",
            "TJX",
            "MDLZ",
            "CL",
            "EL",
        ),
    ),
    Watchlist(
        id="utilities-real-assets",
        name="Utilities / Real Assets",
        description="Defensive utilities, infrastructure, and real asset leaders.",
        tickers=(
            "NEE",
            "SO",
            "DUK",
            "AEP",
            "SRE",
            "D",
            "EXC",
            "XEL",
            "PLD",
            "AMT",
            "EQIX",
            "CCI",
            "WELL",
            "PSA",
            "O",
        ),
    ),
    Watchlist(
        id="nasdaq-growth",
        name="Nasdaq Growth",
        description="Liquid growth leaders from Nasdaq-heavy sectors.",
        tickers=(
            "NVDA",
            "AAPL",
            "MSFT",
            "AMZN",
            "META",
            "GOOGL",
            "AVGO",
            "TSLA",
            "NFLX",
            "COST",
            "AMD",
            "ADBE",
            "PEP",
            "QCOM",
            "AMAT",
        ),
    ),
)


def list_watchlists() -> list[dict[str, object]]:
    return [
        {
            "id": watchlist.id,
            "name": watchlist.name,
            "description": watchlist.description,
            "tickers": list(watchlist.tickers),
            "count": len(watchlist.tickers),
        }
        for watchlist in WATCHLISTS
    ]
