from dataclasses import dataclass


COMPANY_NAMES = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "NVDA": "NVIDIA Corporation",
    "AMZN": "Amazon.com, Inc.",
    "GOOGL": "Alphabet Inc. Class A",
    "META": "Meta Platforms, Inc.",
    "AVGO": "Broadcom Inc.",
    "TSLA": "Tesla, Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "V": "Visa Inc.",
    "MA": "Mastercard Incorporated",
    "BRK-B": "Berkshire Hathaway Inc. Class B",
    "UNH": "UnitedHealth Group Incorporated",
    "LLY": "Eli Lilly and Company",
    "JNJ": "Johnson & Johnson",
    "ABBV": "AbbVie Inc.",
    "XOM": "Exxon Mobil Corporation",
    "CVX": "Chevron Corporation",
    "CAT": "Caterpillar Inc.",
    "GE": "GE Aerospace",
    "HON": "Honeywell International Inc.",
    "COST": "Costco Wholesale Corporation",
    "WMT": "Walmart Inc.",
    "PG": "Procter & Gamble Company",
    "KO": "Coca-Cola Company",
    "PEP": "PepsiCo, Inc.",
    "NEE": "NextEra Energy, Inc.",
    "LIN": "Linde plc",
    "PLD": "Prologis, Inc.",
    "AMT": "American Tower Corporation",
    "ORCL": "Oracle Corporation",
    "CRM": "Salesforce, Inc.",
    "ADBE": "Adobe Inc.",
    "NOW": "ServiceNow, Inc.",
    "AMD": "Advanced Micro Devices, Inc.",
    "INTC": "Intel Corporation",
    "QCOM": "QUALCOMM Incorporated",
    "TXN": "Texas Instruments Incorporated",
    "ANET": "Arista Networks, Inc.",
    "PANW": "Palo Alto Networks, Inc.",
    "CRWD": "CrowdStrike Holdings, Inc.",
    "TSM": "Taiwan Semiconductor Manufacturing Company Limited",
    "ASML": "ASML Holding N.V.",
    "AMAT": "Applied Materials, Inc.",
    "LRCX": "Lam Research Corporation",
    "KLAC": "KLA Corporation",
    "MU": "Micron Technology, Inc.",
    "MRVL": "Marvell Technology, Inc.",
    "ARM": "Arm Holdings plc",
    "SMCI": "Super Micro Computer, Inc.",
    "BAC": "Bank of America Corporation",
    "WFC": "Wells Fargo & Company",
    "GS": "Goldman Sachs Group, Inc.",
    "MS": "Morgan Stanley",
    "C": "Citigroup Inc.",
    "AXP": "American Express Company",
    "BLK": "BlackRock, Inc.",
    "SCHW": "Charles Schwab Corporation",
    "CB": "Chubb Limited",
    "MMC": "Marsh & McLennan Companies, Inc.",
    "AIG": "American International Group, Inc.",
    "ICE": "Intercontinental Exchange, Inc.",
    "MRK": "Merck & Co., Inc.",
    "ABT": "Abbott Laboratories",
    "TMO": "Thermo Fisher Scientific Inc.",
    "ISRG": "Intuitive Surgical, Inc.",
    "DHR": "Danaher Corporation",
    "AMGN": "Amgen Inc.",
    "PFE": "Pfizer Inc.",
    "BSX": "Boston Scientific Corporation",
    "SYK": "Stryker Corporation",
    "MDT": "Medtronic plc",
    "GILD": "Gilead Sciences, Inc.",
    "LMT": "Lockheed Martin Corporation",
    "RTX": "RTX Corporation",
    "NOC": "Northrop Grumman Corporation",
    "GD": "General Dynamics Corporation",
    "BA": "Boeing Company",
    "DE": "Deere & Company",
    "ETN": "Eaton Corporation plc",
    "EMR": "Emerson Electric Co.",
    "PH": "Parker Hannifin Corporation",
    "UNP": "Union Pacific Corporation",
    "UPS": "United Parcel Service, Inc.",
    "URI": "United Rentals, Inc.",
    "COP": "ConocoPhillips",
    "EOG": "EOG Resources, Inc.",
    "SLB": "Schlumberger Limited",
    "MPC": "Marathon Petroleum Corporation",
    "PSX": "Phillips 66",
    "VLO": "Valero Energy Corporation",
    "OXY": "Occidental Petroleum Corporation",
    "HAL": "Halliburton Company",
    "BKR": "Baker Hughes Company",
    "WMB": "Williams Companies, Inc.",
    "KMI": "Kinder Morgan, Inc.",
    "OKE": "ONEOK, Inc.",
    "LNG": "Cheniere Energy, Inc.",
    "MCD": "McDonald's Corporation",
    "SBUX": "Starbucks Corporation",
    "NKE": "NIKE, Inc.",
    "HD": "Home Depot, Inc.",
    "LOW": "Lowe's Companies, Inc.",
    "TGT": "Target Corporation",
    "TJX": "TJX Companies, Inc.",
    "MDLZ": "Mondelez International, Inc.",
    "CL": "Colgate-Palmolive Company",
    "EL": "Estee Lauder Companies Inc.",
    "SO": "Southern Company",
    "DUK": "Duke Energy Corporation",
    "AEP": "American Electric Power Company, Inc.",
    "SRE": "Sempra",
    "D": "Dominion Energy, Inc.",
    "EXC": "Exelon Corporation",
    "XEL": "Xcel Energy Inc.",
    "EQIX": "Equinix, Inc.",
    "CCI": "Crown Castle Inc.",
    "WELL": "Welltower Inc.",
    "PSA": "Public Storage",
    "O": "Realty Income Corporation",
    "NFLX": "Netflix, Inc.",
}


@dataclass(frozen=True)
class Watchlist:
    id: str
    name: str
    description: str
    tickers: tuple[str, ...]


WATCHLISTS = (
    Watchlist(
        id="quality-core",
        name="All Quality",
        description="Large, liquid US leaders across major sectors.",
        tickers=(
            "AAPL",
            "MSFT",
            "NVDA",
            "AMZN",
            "GOOGL",
            "META",
            "AVGO",
            "TSLA",
            "JPM",
            "V",
            "MA",
            "BRK-B",
            "UNH",
            "LLY",
            "JNJ",
            "ABBV",
            "XOM",
            "CVX",
            "CAT",
            "GE",
            "HON",
            "COST",
            "WMT",
            "PG",
            "KO",
            "PEP",
            "NEE",
            "LIN",
            "PLD",
            "AMT",
        ),
    ),
    Watchlist(
        id="technology",
        name="Technology",
        description="Mega-cap software, platforms, payments, and infrastructure.",
        tickers=(
            "AAPL",
            "MSFT",
            "NVDA",
            "AVGO",
            "ORCL",
            "CRM",
            "ADBE",
            "NOW",
            "AMD",
            "INTC",
            "QCOM",
            "TXN",
            "ANET",
            "PANW",
            "CRWD",
        ),
    ),
    Watchlist(
        id="ai-semiconductors",
        name="AI / Semiconductors",
        description="Semiconductor and AI infrastructure leaders.",
        tickers=(
            "NVDA",
            "AVGO",
            "AMD",
            "TSM",
            "ASML",
            "AMAT",
            "LRCX",
            "KLAC",
            "MU",
            "MRVL",
            "QCOM",
            "TXN",
            "ARM",
            "ANET",
            "SMCI",
        ),
    ),
    Watchlist(
        id="financials",
        name="Financials",
        description="Large banks, card networks, asset managers, and insurers.",
        tickers=(
            "JPM",
            "BAC",
            "WFC",
            "GS",
            "MS",
            "C",
            "V",
            "MA",
            "AXP",
            "BLK",
            "SCHW",
            "CB",
            "MMC",
            "AIG",
            "ICE",
        ),
    ),
    Watchlist(
        id="healthcare",
        name="Healthcare",
        description="Large pharma, managed care, devices, and diagnostics.",
        tickers=(
            "LLY",
            "UNH",
            "JNJ",
            "ABBV",
            "MRK",
            "ABT",
            "TMO",
            "ISRG",
            "DHR",
            "AMGN",
            "PFE",
            "BSX",
            "SYK",
            "MDT",
            "GILD",
        ),
    ),
    Watchlist(
        id="defense-industrials",
        name="Defense / Industrials",
        description="Defense primes, aerospace, machinery, and industrial leaders.",
        tickers=(
            "LMT",
            "RTX",
            "NOC",
            "GD",
            "BA",
            "GE",
            "CAT",
            "DE",
            "HON",
            "ETN",
            "EMR",
            "PH",
            "UNP",
            "UPS",
            "URI",
        ),
    ),
    Watchlist(
        id="energy",
        name="Energy",
        description="Large integrated energy, producers, and oilfield services.",
        tickers=(
            "XOM",
            "CVX",
            "COP",
            "EOG",
            "SLB",
            "MPC",
            "PSX",
            "VLO",
            "OXY",
            "HAL",
            "BKR",
            "WMB",
            "KMI",
            "OKE",
            "LNG",
        ),
    ),
    Watchlist(
        id="consumer",
        name="Consumer Leaders",
        description="Consumer staples and durable discretionary leaders.",
        tickers=(
            "COST",
            "WMT",
            "PG",
            "KO",
            "PEP",
            "MCD",
            "SBUX",
            "NKE",
            "HD",
            "LOW",
            "TGT",
            "TJX",
            "MDLZ",
            "CL",
            "EL",
        ),
    ),
    Watchlist(
        id="utilities-real-assets",
        name="Utilities / Real Assets",
        description="Defensive utilities, infrastructure, and real asset leaders.",
        tickers=(
            "NEE",
            "SO",
            "DUK",
            "AEP",
            "SRE",
            "D",
            "EXC",
            "XEL",
            "PLD",
            "AMT",
            "EQIX",
            "CCI",
            "WELL",
            "PSA",
            "O",
        ),
    ),
    Watchlist(
        id="nasdaq-growth",
        name="Nasdaq Growth",
        description="Liquid growth leaders from Nasdaq-heavy sectors.",
        tickers=(
            "NVDA",
            "AAPL",
            "MSFT",
            "AMZN",
            "META",
            "GOOGL",
            "AVGO",
            "TSLA",
            "NFLX",
            "COST",
            "AMD",
            "ADBE",
            "PEP",
            "QCOM",
            "AMAT",
        ),
    ),
)


def list_watchlists() -> list[dict[str, object]]:
    return [
        {
            "id": "smart-universe",
            "name": "Smart Universe",
            "description": (
                "Dynamic diversified selection ranked by relative strength, trend, "
                "liquidity, and volatility."
            ),
            "tickers": [],
            "companies": [],
            "count": "dynamic",
            "dynamic": True,
        },
        *[
        {
            "id": watchlist.id,
            "name": watchlist.name,
            "description": watchlist.description,
            "tickers": list(watchlist.tickers),
            "companies": [
                {
                    "ticker": ticker,
                    "name": COMPANY_NAMES.get(ticker, ticker),
                }
                for ticker in watchlist.tickers
            ],
            "count": len(watchlist.tickers),
        }
        for watchlist in WATCHLISTS
        ],
    ]
